// Generated by nitro
import type { Serialize, Simplify } from "nitropack/types";
declare module "nitropack/types" {
  type Awaited<T> = T extends PromiseLike<infer U> ? Awaited<U> : T
  interface InternalApi {
    '/__nuxt_error': {
      'default': Simplify<Serialize<Awaited<ReturnType<typeof import('../../node_modules/.pnpm/nuxt@3.13.2_eslint@9.18.0_rollup@2.79.2_sass-embedded@1.83.4_typescript@5.6.3_vite@6.0.11_vue-tsc@2.1.8/node_modules/nuxt/dist/core/runtime/nitro/renderer').default>>>>
    }
    '/api/_nuxt_icon/:collection': {
      'default': Simplify<Serialize<Awaited<ReturnType<typeof import('../../node_modules/.pnpm/@nuxt+icon@1.10.3_rollup@2.79.2_vite@6.0.11_vue@3.5.13/node_modules/@nuxt/icon/dist/runtime/server/api').default>>>>
    }
    '/_ipx/**': {
      'default': Simplify<Serialize<Awaited<ReturnType<typeof import('../../node_modules/.pnpm/@nuxt+image@1.8.1_rollup@2.79.2/node_modules/@nuxt/image/dist/runtime/ipx').default>>>>
    }
  }
}
export {}