/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-router. ‼️ DO NOT MODIFY THIS FILE ‼️
// It's recommended to commit this file.
// Make sure to add this file to your tsconfig.json file as an "includes" or "files" entry.

declare module 'vue-router/auto-routes' {
  import type {
    RouteRecordInfo,
    ParamValue,
    ParamValueOneOrMore,
    ParamValueZeroOrMore,
    ParamValueZeroOrOne,
  } from 'vue-router'

  /**
   * Route name map generated by unplugin-vue-router
   */
  export interface RouteNamedMap {
    'index': RouteRecordInfo<'index', '/', Record<never, never>, Record<never, never>>,
    'all': RouteRecordInfo<'all', '/:all(.*)*', { all?: ParamValueZeroOrMore<true> }, { all?: ParamValueZeroOrMore<false> }>,
    'deciphering-big-data': RouteRecordInfo<'deciphering-big-data', '/deciphering-big-data', Record<never, never>, Record<never, never>>,
    'deciphering-big-data-artefacts-and-activities': RouteRecordInfo<'deciphering-big-data-artefacts-and-activities', '/deciphering-big-data/artefacts-and-activities', Record<never, never>, Record<never, never>>,
    'deciphering-big-data-professional-skills-matrix-and-action-plan': RouteRecordInfo<'deciphering-big-data-professional-skills-matrix-and-action-plan', '/deciphering-big-data/professional-skills-matrix-and-action-plan', Record<never, never>, Record<never, never>>,
    'deciphering-big-data-references': RouteRecordInfo<'deciphering-big-data-references', '/deciphering-big-data/references', Record<never, never>, Record<never, never>>,
    'deciphering-big-data-reflection': RouteRecordInfo<'deciphering-big-data-reflection', '/deciphering-big-data/reflection', Record<never, never>, Record<never, never>>,
    'visualising-data': RouteRecordInfo<'visualising-data', '/visualising-data', Record<never, never>, Record<never, never>>,
    'visualising-data-artefacts-and-activities': RouteRecordInfo<'visualising-data-artefacts-and-activities', '/visualising-data/artefacts-and-activities', Record<never, never>, Record<never, never>>,
    'visualising-data-professional-skills-matrix-and-action-plan': RouteRecordInfo<'visualising-data-professional-skills-matrix-and-action-plan', '/visualising-data/professional-skills-matrix-and-action-plan', Record<never, never>, Record<never, never>>,
    'visualising-data-references': RouteRecordInfo<'visualising-data-references', '/visualising-data/references', Record<never, never>, Record<never, never>>,
    'visualising-data-reflection': RouteRecordInfo<'visualising-data-reflection', '/visualising-data/reflection', Record<never, never>, Record<never, never>>,
  }
}
