// generated by the @nuxtjs/tailwindcss <https://github.com/nuxt-modules/tailwindcss> module at 4/21/2025, 1:36:03 AM
const configMerger = require("/Users/adewaleelvah/Documents/elvah/Projects/Data-science eportfolio/node_modules/.pnpm/@nuxtjs+tailwindcss@6.12.2_magicast@0.3.5_rollup@4.32.0/node_modules/@nuxtjs/tailwindcss/dist/runtime/merger.js");

const inlineConfig = {"content":[],"theme":{"extend":{}},"plugins":[]};

const config = [
require("./../tailwind.config.js")
].reduce((prev, curr) => configMerger(curr, prev), configMerger(inlineConfig, { content: { files: ["/Users/adewaleelvah/Documents/elvah/Projects/Data-science eportfolio/components/**/*.{vue,js,jsx,mjs,ts,tsx}","/Users/adewaleelvah/Documents/elvah/Projects/Data-science eportfolio/components/global/**/*.{vue,js,jsx,mjs,ts,tsx}","/Users/adewaleelvah/Documents/elvah/Projects/Data-science eportfolio/components/**/*.{vue,js,jsx,mjs,ts,tsx}","/Users/adewaleelvah/Documents/elvah/Projects/Data-science eportfolio/layouts/**/*.{vue,js,jsx,mjs,ts,tsx}","/Users/adewaleelvah/Documents/elvah/Projects/Data-science eportfolio/pages/**/*.{vue,js,jsx,mjs,ts,tsx}","/Users/adewaleelvah/Documents/elvah/Projects/Data-science eportfolio/plugins/**/*.{js,ts,mjs}","/Users/adewaleelvah/Documents/elvah/Projects/Data-science eportfolio/composables/**/*.{js,ts,mjs}","/Users/adewaleelvah/Documents/elvah/Projects/Data-science eportfolio/utils/**/*.{js,ts,mjs}","/Users/adewaleelvah/Documents/elvah/Projects/Data-science eportfolio/{A,a}pp.{vue,js,jsx,mjs,ts,tsx}","/Users/adewaleelvah/Documents/elvah/Projects/Data-science eportfolio/{E,e}rror.{vue,js,jsx,mjs,ts,tsx}","/Users/adewaleelvah/Documents/elvah/Projects/Data-science eportfolio/app.config.{js,ts,mjs}"] } }));

module.exports = (() => {const cfg=config;cfg["darkMode"] = ["selector","[class~=\"dark\"]"];;return cfg;})()
